### ISSUE TITLE
incorrect patch assessment results - manual analysis

### ISSUE THREAD

**Issue by ngocpq** [KTH/quixbugs-experiment#11]
Hi,
I found an incorrect result in the manual analysis of a patch "[detect_cycle_NPEFix_p3](https://github.com/KTH/quixbugs-experiment/blob/master/patchedPrograms/detect_cycle/NPEFix/patch_detect_cycle_NPEFix_3.diff)" in your paper "**[A Comprehensive Study of Automatic Program Repair on the QuixBugs Benchmark](https://ieeexplore.ieee.org/document/8665475)**, in: 2019 IEEE 1st Int. Work. Intell. Bug Fixing"

The patched code is as follow:
```Java
public static boolean detect_cycle(java_programs.Node node) {
    java_programs.Node hare = node;
    java_programs.Node tortoise = node;
    while (true) {
        if (hare == null) {
            if ((tortoise.getSuccessor()) == null)
                return false;

        }else {
            if ((hare.getSuccessor()) == null)
                return false;

        }
        tortoise = tortoise.getSuccessor();
        hare = hare.getSuccessor().getSuccessor();
        if (hare == tortoise)
            return true;
    } 
}
```

Calling this method with "**null**" value will raise the null reference exception at line "if (tortoise.getSuccessor() == null)" in the first iteration of the loop.

However, in your manual analysis results, this patch is marked as "correct". 
So, if you share the explanation of the manually analysis of other patches, it would be a great help.

Thank you

**Comment by SophieHYe** [comment]
Hi @ngocpq,

Thanks very much for your feedback and interest. 
You are correct. It is misclassified. We probably only focus on the latter part which is equivalent to the reference patch and miss the new bug introduced. 
I am sorry for the mistake and thanks again for pointing it out.

**Comment by ngocpq** [comment]
Hi @SophieHYe ,

Classifying the correctness of patches, especially those that generated automatically by tools, is not easy at all. You have done a great work.
Thank you for your work and effort to classify patches in this benchmark.

**Comment by SophieHYe** [comment]
@ngocpq,
Thanks for the feedback, you point actually remind us classifying patch correctness should both consider the correct fix for the existing bug and possible new bug introduced. Thanks.
