### ISSUE TITLE
What was the time budget set for each repair attempt?

### ISSUE THREAD

**Issue by MaximoOliveira** [KTH/quixbugs-experiment#17]
Hello!

Thank you for this interesting study on QuixBugs!

I read [A Comprehensive Study of Automatic Program Repair on the QuixBugs Benchmark](https://arxiv.org/pdf/1805.03454.pdf) and did not find any information regarding the time budget set for each program that is being repaired.

For [RepairThemAll](https://arxiv.org/pdf/1905.11973.pdf) I found it was two hours: 

> For this experiment, we set the time budget to **two hours per repair attempt**: a repair attempt consists of the execution of one repair tool over one bug.

Do you know what the time budget you gave for each tool, in this particular study?

Thank you!

**Comment by martinezmatias** [comment]
Hi @MaximoOliveira 
> Do you know what the time budget you gave for each tool, in this particular study?

Even I am not sure, I would say that we used the time budget associated to each repair tool we run. For Astor we used 1 or 2 hours for each repair attempts (ie., repairing one single bug), but not more than that. 

Regards
Matias

**Comment by MaximoOliveira** [comment]
Thank you Matias!

Wouldn't it skew the results though if for example for a certain tool we set the max time limit for 10+ hours and for others 1 or 2 hours?

The tool that has 10+ hours per attempt would be able to try more attempts and thus possibly present better results.

I doubt there was a tool that used 10+ hours per attempt, but even if there is one that uses 4 hours while others use 2 hours it wouldn't be fair, wouldn't you agree?

Regards,
Máximo Oliveira

**Comment by martinezmatias** [comment]
Hi @MaximoOliveira 

We use the same timeout for all the repair attempts (I dont remember if it was 1 or 2 hours).

> The tool that has 10+ hours per attempt would be able to try more attempts and thus possibly present better results.

In theory yes: if you allocate more time budget, the tool will have more time to navigate the search space.
However, in practice, the navigation of the search space is dominated by the execution of test cases (the failing or the regression). The number of candidate patches evaluated is different across the buggy program. Example, if you have one buggy program A which was one failing test that takes 30 seconds to run, and another buggy program B which failing test takes 1 second, then the repair tool will evaluate more candidate patches of B than from A.

**Comment by MaximoOliveira** [comment]
Thank you once again @martinezmatias !
