### ISSUE TITLE
QuixBugs Preconditions

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [KTH/quixbugs-experiment#18]
Hi,

In the paper with the title "A comprehensive study of automatic program repair on the QuixBugs benchmark," it is mentioned that preconditions of these 40 programs are available in this repository. But I cannot find them.

Where can I find these preconditions?

Thank you for your time and consideration in advance.

Best Wishes,
Amirfarhad

**Comment by martinezmatias** [comment]
Hi @Amirfarhad-Nilizadeh 

Please see in the [Folder structure](https://github.com/KTH/quixbugs-experiment#folder-structure) section of the main [Readme](https://github.com/KTH/quixbugs-experiment/blob/master/README.md) the organization of the repo. In particular, the 40 buggy programs are [here](https://github.com/KTH/quixbugs-experiment/tree/master/src/main/java/java_programs).

Regards
Matias

**Comment by Amirfarhad-Nilizadeh** [comment]
Hi @martinezmatias 

Thank you for your quick response. My question is about **input preconditions** for QuixBugs, not programs source code.

In the paper, there is a subsection with the name "Input preconditions" in the section 4.1 that says, "Preconditions of the input domain for each program are important in our study as we use them as the constraints to automatically generate patches and to discard overfitting patches. We computed them for the 40 programs.  **All preconditions are given in our online appendix.**"

However, I cannot find these preconditions. I was expecting some informal specifications like the one is explained for program GET_FACTOR as a sample in the paper in the continuation of the same subsection. Or maybe formal preconditions like using Java Modeling Language.

Is any informal or formal description available for input domains as discussed in the paper?

Thank you for your time and help in advance.

Best Wishes,
Amirfarhad
